### ISSUE TITLE
Impossible to install it via vd GUI

### ISSUE THREAD

**Issue by aborruso** [aswan89/visidata_plugin_genericSQL#1]
First of all thank you for this plugin.

I have just installed the develop version, and it's impossible to install it via GUI. I have this error.

How to solve it?

Thank you

![image](https://user-images.githubusercontent.com/30607/80118178-5701be80-8588-11ea-9bd3-b059fcd7163a.png)

**Comment by aswan89** [comment]
That's my fault, there must have been a space or something that got added to the source file and screwed up the hash I added to the Visidata repository. I'll open a request with them to fix it, but in the mean time you can probably copy the source file to `$HOME/.visidata` and install the dependencies yourself.

**Comment by aswan89** [comment]
@aborruso The Visidata folks accepted the hash change I requested, could you update your version of visidata and check that the plugin is working now?

**Comment by aborruso** [comment]
Solved, thank you
